FROM nginx

MAINTAINER lciclcAzz

RUN echo '\
<!DOCTYPE html>\
<html lang="en">\
<head>\
    <meta charset="utf-8">\
    <title>lciclcAzz Profile</title>\
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">\
</head>\
<body>\
    <div class="container">\
        <div class="row">\
            <div class="col-md-12 text-center">\
                <h2>lciclcAzz</h2>\
                <br/>\
            </div>\
        </div>\
        <div class="row">\
            <div class="col-md-12 text-center">\
                <div>\
                    <img src="http://graph.facebook.com/100001887212842/picture?width=250" class="img-thumbnail">\
                    <div>\
                        <h3> lciclcAzz </h3>\
                        <h5> <strong> IT Security And Developer </strong></h5>\
                        <p>Sometime It is Good To Break The Roles</p>\
                        <hr>\
                        <a href="#" class="btn btn-default btn-sm">Facebook </a>\
                        <a href="#" class="btn btn-default btn-sm">Google</a>\
                        <a href="#" class="btn btn-default btn-sm">Twitter </a>\
                        <a href="https://lciclcazz.wordpress.com" class="btn btn-default btn-sm">Blog </a>\
                    </div>\
                </div>\
            </div>\
        </div>\
    </div>\
</body>\
</html>\
'\
> /usr/share/nginx/html/index.html