version: "2"
services:

    lb:
      image: dockercloud/haproxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
      links:
        - proxy

      proxy:
        image: nginx
        ports:
        - 80:80
        networks:
        - net
        depends_on:
        - app
        hostname: proxy
        container_name: proxy

      app:
        image: tomcat
        ports:
        - 8080
        networks:
        - net
        depends_on:
        - mongodb
        hostname: app

      mongodb:
        image: mongodb
        ports:
        - 27017:27017
        networks:
        - net
        depends_on:
        - elk
        hostname: mongodb
        container_name: mongodb
        volumes:
        - music_data:/data/db
        - music_data:/data/configdb

      elk:
        image: sebp/elk:latest
        ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044
        - 5000:5000
        networks:
        - net
        volumes:
        - music_elk:/var/lib/elasticsearch
        hostname: elk
        container_name: elk




